### ISSUE TITLE
make & update `navigation` component

### ISSUE THREAD

**Issue by serapath** [playproject-io/smartcontract.codes#10]
## `@todo`
* [x] make pagination component
* [x] fix pagination
* [ ] pagination jumps when search in progress
* [ ] change current pagination to PDF reader's style ( << [ ] / 234 >> )

---
