### ISSUE TITLE
advanced search

### ISSUE THREAD

**Issue by serapath** [playproject-io/smartcontract.codes#11]
## `@todo`
* [ ] make and refine UX/UI concept for advanced search
    * [ ] create search type UI components
    * [ ] decide for and implement predefined search filters

---
