### ISSUE TITLE
create search type UI components

### ISSUE THREAD

**Issue by serapath** [playproject-io/smartcontract.codes#12]
## `@todo`
* [ ] make search type: `solidity version`
    * [ ] UI component
    * [ ] AST analysis module
* [ ] make search type: `publish date`
    * [ ] UI component
    * [ ] analysis module
* [ ] make search type: `dependencies`
    * [ ] UI component
    * [ ] AST analysis module
* [ ] make search type: `text`
    * [ ] UI component
    * [ ] analysis module
* [ ] make search type: `audited`
    * [ ] UI component
    * [ ] information retrieval module
* [ ] make search type: `verified`
    * [ ] UI component
    * [ ] analysis module

---
