### ISSUE TITLE
smartcontract.codes concept & updates

### ISSUE THREAD

**Issue by serapath** [playproject-io/smartcontract.codes#6]
## `@todo`
* [x] mock array of ~1000 contract addresses
* [x] fetch and store X=6 of 1000 contract address data (sourcecode, ...) and cache it in indexDB
* [x] display a list of boxes on the page, each box shows address + more meta information about * [ ] contract (like title, publish date, author?, ....)
* [x] have at the top and/or bottom a NEXT and PREVIOUS and maybe (FIRST and LAST) page to show the next 6 boxes
* [x] update the url with e.g. (#page=23) so somebody can copy paste the link and get to the same page again
* [x] when you click a box, it should switch to editor view which you can click "CLOSE" to return to the list of boxes view
* [ ] [`smartcontract.codes#3`: fix broken english on smartcontract.codes and in the editor](https://github.com/playproject-io/smartcontract.codes/issues/3)

---
