### ISSUE TITLE
make & update `card` component

### ISSUE THREAD

**Issue by serapath** [playproject-io/smartcontract.codes#8]
## `@todo`
* [x] make card component
* [x] make card responsive also on very small width
* [ ] implement code mirror
    * (to get syntax highlighting, line breaks/responsivenes of the code)
* [ ] implement custom nicely styled scrollbar to see the code when on hover
    * up & down, left & right
* [ ] make custom play-ed theme for solidity syntax highlighting

---
